from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from backend.database import get_db
from backend.models import DimProducts, FactInventorySnapshots, FactRollingInventory, FactPurchasePlans, PlanningPolicies, SeasonalFactors, FactForecasts
from datetime import date, timedelta
import pandas as pd

router = APIRouter(
    prefix="/api/planning/order-plan",
    tags=["Order Planning"]
)

@router.get("")
def get_order_plan(db: Session = Depends(get_db)):
    """
    Generate Order Plan view (Sheet ORDER equivalent).
    """
    # 1. Fetch Products
    products = db.query(DimProducts).all()
    
    # 2. Fetch Latest Stock
    # Improve: Batch fetch
    stock_map = {}
    snaps = db.query(FactInventorySnapshots).all()
    for s in snaps:
        stock_map[s.sku_id] = s.quantity_on_hand

    # 3. Fetch Policies
    default_policy = db.query(PlanningPolicies).filter_by(is_default=True).first()
    safety_days = default_policy.safety_stock_days if default_policy else 30 # Default 1 month if missing
    
    # 4. Fetch Forecasts (Next 3 months)
    today = date.today()
    start_date = today.replace(day=1)
    end_date = (start_date + timedelta(days=100)) # Approx 3 months
    
    forecasts = db.query(FactForecasts).filter(
        FactForecasts.forecast_date >= start_date,
        FactForecasts.forecast_date <= end_date
    ).all()
    
    fcst_map = {}
    for f in forecasts:
        if f.sku_id not in fcst_map: fcst_map[f.sku_id] = {}
        # Key by relative month index (0, 1, 2)
        # simplistic: just use month number
        fcst_map[f.sku_id][f.forecast_date.month] = f.quantity_predicted

    # 5. Fetch Seasonality
    seasonal = db.query(SeasonalFactors).all()
    seasonal_map = {s.month: s.demand_multiplier for s in seasonal}

    # 6. Build Result
    results = []
    current_month = today.month
    next_month = (today.replace(day=28) + timedelta(days=4)).month
    month_3 = (today.replace(day=28) + timedelta(days=35)).month # Approx

    for p in products:
        current_stock = stock_map.get(p.sku_id, 0)
        
        # Forecasts (Apply Seasonality if not already in forecast table? Assuming forecast table is raw or adjusted? 
        # Usually forecast engine applies it. Here we assume we might need to apply if it's raw. 
        # For MVP, assume forecast table HAS seasonality OR we apply it here. 
        # Let's apply multiplier here for safety if "SMA" is used which is raw.)
        
        m1_base = fcst_map.get(p.sku_id, {}).get(current_month, 0)
        m2_base = fcst_map.get(p.sku_id, {}).get(next_month, 0)
        
        # Apply Multiplier (Example)
        m1_factor = seasonal_map.get(current_month, 1.0)
        m2_factor = seasonal_map.get(next_month, 1.0)
        
        f_m1 = m1_base * m1_factor
        f_m2 = m2_base * m2_factor
        
        # Safety Stock Calculation (3 Months Average * Safety Days?)
        # Doc Trigger: "Safety Stock = 3 months" (Fixed Quantity? Or coverage?)
        # "Safety Stock = 3 months" implies coverage of 3 months demand.
        # So Target Stock = Sum(Next 3 Months Demand).
        
        avg_monthly = (f_m1 + f_m2) / 2 if (f_m1 + f_m2) > 0 else 0
        
        # If policy is 90 days (3 months), then safety stock = 3 * Avg Monthly
        target_stock = avg_monthly * 3 
        
        # Suggested Order
        # Suggested = Target - (Current + OnOrder)
        # OnOrder not fully tracked in snapshot yet? Assume 0 for now or fetch from POs.
        on_order = 0 # Placeholder
        
        suggested = target_stock - (current_stock + on_order)
        if suggested < 0: suggested = 0
        
        # MOQ Rounding
        if p.moq and suggested > 0 and suggested < p.moq:
            suggested = p.moq

        results.append({
            "sku_id": p.sku_id,
            "product_name": p.product_name,
            "current_stock": current_stock,
            "stock_on_order": on_order,
            "safety_stock": round(target_stock, 2),
            "lead_time_days": p.supplier_lead_time_days or 7,
            "avg_sales": 0, # To be calc from history
            "forecast_month_1": round(f_m1, 2),
            "forecast_month_2": round(f_m2, 2),
            "forecast_month_3": 0,
            "suggested_order": round(suggested, 2),
            "notes": "Generated by Order Plan"
        })
        
    return results
